### ISSUE TITLE
Please comment in this issue to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/sep-22-developers#2]
👋  Please tell us -- where are you joining us from?

**Comment by hectorsector** [comment]
Hello!

**Comment by githubteacher** [comment]
:tada: @hectorsector is now a repository collaborator. :balloon:

**Comment by vforvangelis** [comment]
Hello from Athens, Greece! :wave:

**Comment by iamallyniam** [comment]
hi

**Comment by DCPRevere** [comment]
Hello from London, UK.

**Comment by senthilvaradha** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @vforvangelis, @iamallyniam, and @DCPRevere are now  repository collaborators. :balloon:

**Comment by rlubos** [comment]
Hi!

**Comment by yagee-de** [comment]
I like :metal:

**Comment by eken378** [comment]
Hi

**Comment by appijumbo** [comment]
Hello from the UK :)

**Comment by ssathya** [comment]
My comment

**Comment by X22** [comment]
Yo!

**Comment by osundblad** [comment]
Hello from Stockholm, Sweden

**Comment by dabeah** [comment]
Hejsan!

**Comment by AMill7** [comment]
hi

**Comment by smitley** [comment]
Hello!

**Comment by manojhl** [comment]
Hello all, I'm from Bangalore, India

**Comment by kkrebs** [comment]
I'm from Potsdam, Germany

**Comment by hubertmis** [comment]
Hello

**Comment by deepkotecha** [comment]
Hello from India!

**Comment by chfisher1978** [comment]
hi

**Comment by eckstueck** [comment]
:wave: from Jena, Germany

**Comment by pszkotak** [comment]
Hi

**Comment by erikScania** [comment]
Hi :)

**Comment by ahialy** [comment]
Bonjour from Quebec City, Canada !

**Comment by githubteacher** [comment]
:tada: @vskin4u, @rlubos, @yagee-de, @eken378, @appijumbo, @ssathya, @X22, @osundblad, @dabeah, @AMill7, @master-smit, @manojhl, @kkrebs, @hubertmis, @deepkotecha, @chfisher1978, @eckstueck, and @pszkotak are now  repository collaborators. :balloon:

**Comment by deepkotecha** [comment]
Hello from India!

**Comment by krlo** [comment]
Hi from Krakow, Poland :)

**Comment by KelKx** [comment]
Hi

**Comment by varunsufi** [comment]
hello

**Comment by sebhofmann** [comment]
Hi 👍

**Comment by ediamin** [comment]
Hello, I'm Edi from Bangladesh. Cheers! :)

**Comment by tadkam** [comment]
hello

**Comment by nikunjdnp** [comment]
Hello

**Comment by ghost** [comment]
Hi, Krakow

**Comment by appijumbo** [comment]
hi

**Comment by prasanjitkhuntia** [comment]
Hi

**Comment by turbox1** [comment]
hi

**Comment by jmoorebb** [comment]
hello!

**Comment by avengerine** [comment]
Hello everyone :)

**Comment by githubteacher** [comment]
:tada: @erikScania, @ahialy, @krlo, @KelKx, @varunsufi, @paschty, @ediamin, @dziku21, @nikunjdnp, @SzymunS, @prasanjitkhuntia, and @turbox1 are now  repository collaborators. :balloon:

**Comment by sunjays** [comment]
hi from a small little town Darmstadt Germany. Cheers

**Comment by nikunjdnp** [comment]
hello everyone..!

**Comment by chetansharma87** [comment]
hi everyone

**Comment by katrinsko** [comment]
Hi from Södertälje, Sweden

**Comment by Abderrahman1** [comment]
Hi Stockholm

**Comment by alst74** [comment]
hey there...

**Comment by wbober** [comment]
Hi

**Comment by githubteacher** [comment]
:tada: @jmoorebb, @avengerine, @sunjays, @chetansharma87, @scatrin, @Abderrahman1, and @alst74 are now  repository collaborators. :balloon:

**Comment by Peter-Eismann** [comment]
Hi

**Comment by LuDuda** [comment]
Hello!

**Comment by rafesilver** [comment]
Brazil

**Comment by lebdim45** [comment]
Hello from Ljubljana! ;)

**Comment by githubteacher** [comment]
:tada: @wbober, @Peter-Eismann, @LuDuda, @rafesilver, and @lebdim45 are now  repository collaborators. :balloon:

**Comment by jhrabovsky** [comment]
Hello!

**Comment by githubteacher** [comment]
:tada: @jhrabovsky is now a repository collaborator. :balloon:

**Comment by radduri** [comment]
Hi

**Comment by darthzyklus** [comment]
hi :) I'm from Venezuela

**Comment by GodfatherX64** [comment]
Hello from Alexandria, Egypt.

**Comment by SrinivasPulla** [comment]
Hi

**Comment by jstephens-cis** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @radduri, @andres-uris, @GodfatherX64, and @SrinivasPulla are now  repository collaborators. :balloon:

**Comment by SrinivasPulla** [comment]
Hi

Thanks,
Srinivas Pulla
Tech Lead
Shore Group Associates LLC
(C) +91-984-866-2373
www.ShoreGroupAssociates.com<http://www.shoregroupassociates.com/>

**Comment by cportilla** [comment]
Hola

**Comment by githubteacher** [comment]
:tada: @jstephens-cis and @cportilla are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
@githubteacher hi!

**Comment by dharindave** [comment]
Hi

**Comment by githubteacher** [comment]
:tada: @dharindave is now a repository collaborator. :balloon:

**Comment by TiloNN** [comment]
Tach! 
I'm from Germany too.

**Comment by githubteacher** [comment]
:tada: @TiloNN is now a repository collaborator. :balloon:

**Comment by prfi** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @prfi is now a repository collaborator. :balloon:

**Comment by lebdim45** [comment]
Hey, again ...
